/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "ccnx_TlvDictionary.h"


#include <stdint.h>		// Use the C99 official header


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_CCNxTlvDictionary_1SchemaVersion_1V0_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  CCNxTlvDictionary_SchemaVersion result;
  
  (void)jenv;
  (void)jcls;
  result = (CCNxTlvDictionary_SchemaVersion)CCNxTlvDictionary_SchemaVersion_V0;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_CCNxTlvDictionary_1SchemaVersion_1V1_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  CCNxTlvDictionary_SchemaVersion result;
  
  (void)jenv;
  (void)jcls;
  result = (CCNxTlvDictionary_SchemaVersion)CCNxTlvDictionary_SchemaVersion_V1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1Create(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  size_t arg1 ;
  size_t arg2 ;
  CCNxTlvDictionary *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (size_t)jarg1; 
  arg2 = (size_t)jarg2; 
  result = (CCNxTlvDictionary *)ccnxTlvDictionary_Create(arg1,arg2);
  *(CCNxTlvDictionary **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1Acquire(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  CCNxTlvDictionary *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  result = (CCNxTlvDictionary *)ccnxTlvDictionary_Acquire((struct ccnx_tlv_dictionary const *)arg1);
  *(CCNxTlvDictionary **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1Release(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CCNxTlvDictionary **arg1 = (CCNxTlvDictionary **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary ***)&jarg1; 
  ccnxTlvDictionary_Release(arg1);
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1PutBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  PARCBuffer *arg3 = (PARCBuffer *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  arg3 = *(PARCBuffer **)&jarg3; 
  result = (bool)ccnxTlvDictionary_PutBuffer(arg1,arg2,(PARCBuffer const *)arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1IsValueBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (bool)ccnxTlvDictionary_IsValueBuffer((struct ccnx_tlv_dictionary const *)arg1,arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1IsValueObject(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (bool)ccnxTlvDictionary_IsValueObject((struct ccnx_tlv_dictionary const *)arg1,arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1GetBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (PARCBuffer *)ccnxTlvDictionary_GetBuffer((struct ccnx_tlv_dictionary const *)arg1,arg2);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1PutInteger(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jobject jarg3) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  uint64_t arg3 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  {
    jclass clazz;
    jmethodID mid;
    jbyteArray ba;
    jbyte* bae;
    jsize sz;
    int i;
    
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "BigInteger null");
      return 0;
    }
    clazz = (*jenv)->GetObjectClass(jenv, jarg3);
    mid = (*jenv)->GetMethodID(jenv, clazz, "toByteArray", "()[B");
    ba = (jbyteArray)(*jenv)->CallObjectMethod(jenv, jarg3, mid);
    bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    sz = (*jenv)->GetArrayLength(jenv, ba);
    arg3 = 0;
    for(i=0; i<sz; i++) {
      arg3 = (arg3 << 8) | (uint64_t const)(unsigned char)bae[i];
    }
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
  }
  result = (bool)ccnxTlvDictionary_PutInteger(arg1,arg2,arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1IsValueInteger(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (bool)ccnxTlvDictionary_IsValueInteger((struct ccnx_tlv_dictionary const *)arg1,arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1GetInteger(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jobject jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (uint64_t)ccnxTlvDictionary_GetInteger((struct ccnx_tlv_dictionary const *)arg1,arg2);
  {
    jbyteArray ba = (*jenv)->NewByteArray(jenv, 9);
    jbyte* bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    jclass clazz = (*jenv)->FindClass(jenv, "java/math/BigInteger");
    jmethodID mid = (*jenv)->GetMethodID(jenv, clazz, "<init>", "([B)V");
    jobject bigint;
    int i;
    
    bae[0] = 0;
    for(i=1; i<9; i++ ) {
      bae[i] = (jbyte)(result>>8*(8-i));
    }
    
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
    bigint = (*jenv)->NewObject(jenv, clazz, mid, ba);
    jresult = bigint;
  }
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1PutName(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  CCNxName *arg3 = (CCNxName *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  arg3 = *(CCNxName **)&jarg3; 
  result = (bool)ccnxTlvDictionary_PutName(arg1,arg2,(CCNxName const *)arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1IsValueName(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (bool)ccnxTlvDictionary_IsValueName((struct ccnx_tlv_dictionary const *)arg1,arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1GetName(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  CCNxName *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (CCNxName *)ccnxTlvDictionary_GetName((struct ccnx_tlv_dictionary const *)arg1,arg2);
  *(CCNxName **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1PutIoVec(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  CCNxCodecNetworkBufferIoVec *arg3 = (CCNxCodecNetworkBufferIoVec *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  arg3 = *(CCNxCodecNetworkBufferIoVec **)&jarg3; 
  result = (bool)ccnxTlvDictionary_PutIoVec(arg1,arg2,(CCNxCodecNetworkBufferIoVec const *)arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1IsValueIoVec(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (bool)ccnxTlvDictionary_IsValueIoVec((struct ccnx_tlv_dictionary const *)arg1,arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1GetIoVec(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  CCNxCodecNetworkBufferIoVec *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (CCNxCodecNetworkBufferIoVec *)ccnxTlvDictionary_GetIoVec((struct ccnx_tlv_dictionary const *)arg1,arg2);
  *(CCNxCodecNetworkBufferIoVec **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1PutListBuffer(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  uint32_t arg3 ;
  PARCBuffer *arg4 = (PARCBuffer *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  arg3 = (uint32_t)jarg3; 
  arg4 = *(PARCBuffer **)&jarg4; 
  result = (bool)ccnxTlvDictionary_PutListBuffer(arg1,arg2,arg3,(PARCBuffer const *)arg4);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1PutJson(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  PARCJSON *arg3 = (PARCJSON *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  arg3 = *(PARCJSON **)&jarg3; 
  result = (bool)ccnxTlvDictionary_PutJson(arg1,arg2,(PARCJSON const *)arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1IsValueJson(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (bool)ccnxTlvDictionary_IsValueJson((struct ccnx_tlv_dictionary const *)arg1,arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1GetJson(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  PARCJSON *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (PARCJSON *)ccnxTlvDictionary_GetJson((struct ccnx_tlv_dictionary const *)arg1,arg2);
  *(PARCJSON **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1PutObject(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  PARCObject *arg3 = (PARCObject *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  arg3 = *(PARCObject **)&jarg3; 
  result = (bool)ccnxTlvDictionary_PutObject(arg1,arg2,(PARCObject const *)arg3);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1GetObject(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  PARCObject *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = (PARCObject *)ccnxTlvDictionary_GetObject((struct ccnx_tlv_dictionary const *)arg1,arg2);
  *(PARCObject **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1ListGetByPosition(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  size_t arg3 ;
  PARCBuffer **arg4 = (PARCBuffer **) 0 ;
  uint32_t *arg5 = (uint32_t *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  arg3 = (size_t)jarg3; 
  arg4 = *(PARCBuffer ***)&jarg4; 
  arg5 = *(uint32_t **)&jarg5; 
  result = (bool)ccnxTlvDictionary_ListGetByPosition((struct ccnx_tlv_dictionary const *)arg1,arg2,arg3,arg4,arg5);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1ListGetByType(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  uint32_t arg3 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  arg3 = (uint32_t)jarg3; 
  result = (PARCBuffer *)ccnxTlvDictionary_ListGetByType((struct ccnx_tlv_dictionary const *)arg1,arg2,arg3);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1ListSize(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  uint32_t arg2 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (uint32_t)jarg2; 
  result = ccnxTlvDictionary_ListSize((struct ccnx_tlv_dictionary const *)arg1,arg2);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1SetMessageType_1Interest(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  CCNxTlvDictionary_SchemaVersion arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (CCNxTlvDictionary_SchemaVersion)jarg2; 
  ccnxTlvDictionary_SetMessageType_Interest(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1SetMessageType_1ContentObject(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  CCNxTlvDictionary_SchemaVersion arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (CCNxTlvDictionary_SchemaVersion)jarg2; 
  ccnxTlvDictionary_SetMessageType_ContentObject(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1SetMessageType_1Control(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  CCNxTlvDictionary_SchemaVersion arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (CCNxTlvDictionary_SchemaVersion)jarg2; 
  ccnxTlvDictionary_SetMessageType_Control(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1SetMessageType_1Manifest(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  CCNxTlvDictionary_SchemaVersion arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (CCNxTlvDictionary_SchemaVersion)jarg2; 
  ccnxTlvDictionary_SetMessageType_Manifest(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1SetMessageType_1InterestReturn(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  CCNxTlvDictionary_SchemaVersion arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (CCNxTlvDictionary_SchemaVersion)jarg2; 
  ccnxTlvDictionary_SetMessageType_InterestReturn(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1GetSchemaVersion(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jint jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  CCNxTlvDictionary_SchemaVersion result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  result = (CCNxTlvDictionary_SchemaVersion)ccnxTlvDictionary_GetSchemaVersion((struct ccnx_tlv_dictionary const *)arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1IsInterest(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  result = (bool)ccnxTlvDictionary_IsInterest((struct ccnx_tlv_dictionary const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1IsInterestReturn(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  result = (bool)ccnxTlvDictionary_IsInterestReturn((struct ccnx_tlv_dictionary const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1IsContentObject(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  result = (bool)ccnxTlvDictionary_IsContentObject((struct ccnx_tlv_dictionary const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1IsControl(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  result = (bool)ccnxTlvDictionary_IsControl((struct ccnx_tlv_dictionary const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1IsManifest(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  result = (bool)ccnxTlvDictionary_IsManifest((struct ccnx_tlv_dictionary const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1GetLifetime(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  struct timeval result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  result = ccnxTlvDictionary_GetLifetime((struct ccnx_tlv_dictionary const *)arg1);
  {
    struct timeval * resultptr = (struct timeval *) malloc(sizeof(struct timeval));
    memmove(resultptr, &result, sizeof(struct timeval));
    *(struct timeval **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1Display(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = (int)jarg2; 
  ccnxTlvDictionary_Display((struct ccnx_tlv_dictionary const *)arg1,arg2);
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1Equals(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  CCNxTlvDictionary *arg2 = (CCNxTlvDictionary *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = *(CCNxTlvDictionary **)&jarg2; 
  result = (bool)ccnxTlvDictionary_Equals((struct ccnx_tlv_dictionary const *)arg1,(struct ccnx_tlv_dictionary const *)arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1ShallowCopy(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  CCNxTlvDictionary *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  result = (CCNxTlvDictionary *)ccnxTlvDictionary_ShallowCopy((struct ccnx_tlv_dictionary const *)arg1);
  *(CCNxTlvDictionary **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1SetMessageInterface(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  CCNxMessageInterface *arg2 = (CCNxMessageInterface *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  arg2 = *(CCNxMessageInterface **)&jarg2; 
  ccnxTlvDictionary_SetMessageInterface(arg1,(CCNxMessageInterface const *)arg2);
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_internal_CcnxTlvDictionary_ccnxTlvDictionary_1GetMessageInterface(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxTlvDictionary *arg1 = (CCNxTlvDictionary *) 0 ;
  CCNxMessageInterface *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxTlvDictionary **)&jarg1; 
  result = (CCNxMessageInterface *)ccnxTlvDictionary_GetMessageInterface((struct ccnx_tlv_dictionary const *)arg1);
  *(CCNxMessageInterface **)&jresult = result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

