/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "ccnx_ContentObject.h"


#include <stdint.h>		// Use the C99 official header


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1CreateWithNameAndPayload(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jlong jresult = 0 ;
  CCNxName *arg1 = (CCNxName *) 0 ;
  PARCBuffer *arg2 = (PARCBuffer *) 0 ;
  CCNxContentObject *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxName **)&jarg1; 
  arg2 = *(PARCBuffer **)&jarg2; 
  result = (CCNxContentObject *)ccnxContentObject_CreateWithNameAndPayload((CCNxName const *)arg1,(PARCBuffer const *)arg2);
  *(CCNxContentObject **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1CreateWithPayload(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  PARCBuffer *arg1 = (PARCBuffer *) 0 ;
  CCNxContentObject *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PARCBuffer **)&jarg1; 
  result = (CCNxContentObject *)ccnxContentObject_CreateWithPayload((PARCBuffer const *)arg1);
  *(CCNxContentObject **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1CreateWithImplAndPayload(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jlong jresult = 0 ;
  CCNxContentObjectInterface *arg1 = (CCNxContentObjectInterface *) 0 ;
  CCNxName *arg2 = (CCNxName *) 0 ;
  CCNxPayloadType arg3 ;
  PARCBuffer *arg4 = (PARCBuffer *) 0 ;
  CCNxPayloadType const *argp3 ;
  CCNxContentObject *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObjectInterface **)&jarg1; 
  arg2 = *(CCNxName **)&jarg2; 
  argp3 = *(CCNxPayloadType **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null CCNxPayloadType const");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = *(PARCBuffer **)&jarg4; 
  result = (CCNxContentObject *)ccnxContentObject_CreateWithImplAndPayload((CCNxContentObjectInterface const *)arg1,(CCNxName const *)arg2,arg3,(PARCBuffer const *)arg4);
  *(CCNxContentObject **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1GetName(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  CCNxName *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  result = (CCNxName *)ccnxContentObject_GetName((CCNxTlvDictionary const *)arg1);
  *(CCNxName **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1GetPayload(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  result = (PARCBuffer *)ccnxContentObject_GetPayload((CCNxTlvDictionary const *)arg1);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1GetPayloadType(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  CCNxPayloadType result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  result = ccnxContentObject_GetPayloadType((CCNxTlvDictionary const *)arg1);
  {
    CCNxPayloadType * resultptr = (CCNxPayloadType *) malloc(sizeof(CCNxPayloadType));
    memmove(resultptr, &result, sizeof(CCNxPayloadType));
    *(CCNxPayloadType **)&jresult = resultptr;
  }
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1SetFinalChunkNumber(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg2) {
  jboolean jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  uint64_t arg2 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  {
    jclass clazz;
    jmethodID mid;
    jbyteArray ba;
    jbyte* bae;
    jsize sz;
    int i;
    
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "BigInteger null");
      return 0;
    }
    clazz = (*jenv)->GetObjectClass(jenv, jarg2);
    mid = (*jenv)->GetMethodID(jenv, clazz, "toByteArray", "()[B");
    ba = (jbyteArray)(*jenv)->CallObjectMethod(jenv, jarg2, mid);
    bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    sz = (*jenv)->GetArrayLength(jenv, ba);
    arg2 = 0;
    for(i=0; i<sz; i++) {
      arg2 = (arg2 << 8) | (uint64_t const)(unsigned char)bae[i];
    }
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
  }
  result = (bool)ccnxContentObject_SetFinalChunkNumber(arg1,arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1HasFinalChunkNumber(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  result = (bool)ccnxContentObject_HasFinalChunkNumber((CCNxTlvDictionary const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1GetFinalChunkNumber(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jobject jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  result = (uint64_t)ccnxContentObject_GetFinalChunkNumber((CCNxTlvDictionary const *)arg1);
  {
    jbyteArray ba = (*jenv)->NewByteArray(jenv, 9);
    jbyte* bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    jclass clazz = (*jenv)->FindClass(jenv, "java/math/BigInteger");
    jmethodID mid = (*jenv)->GetMethodID(jenv, clazz, "<init>", "([B)V");
    jobject bigint;
    int i;
    
    bae[0] = 0;
    for(i=1; i<9; i++ ) {
      bae[i] = (jbyte)(result>>8*(8-i));
    }
    
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
    bigint = (*jenv)->NewObject(jenv, clazz, mid, ba);
    jresult = bigint;
  }
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1SetSignature(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jboolean jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  PARCBuffer *arg2 = (PARCBuffer *) 0 ;
  PARCSignature *arg3 = (PARCSignature *) 0 ;
  CCNxKeyLocator *arg4 = (CCNxKeyLocator *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  arg2 = *(PARCBuffer **)&jarg2; 
  arg3 = *(PARCSignature **)&jarg3; 
  arg4 = *(CCNxKeyLocator **)&jarg4; 
  result = (bool)ccnxContentObject_SetSignature(arg1,(PARCBuffer const *)arg2,(PARCSignature const *)arg3,(CCNxKeyLocator const *)arg4);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1GetKeyId(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  PARCBuffer *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  result = (PARCBuffer *)ccnxContentObject_GetKeyId((CCNxTlvDictionary const *)arg1);
  *(PARCBuffer **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1Acquire(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  CCNxContentObject *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  result = (CCNxContentObject *)ccnxContentObject_Acquire((CCNxTlvDictionary const *)arg1);
  *(CCNxContentObject **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1Release(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CCNxContentObject **arg1 = (CCNxContentObject **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject ***)&jarg1; 
  ccnxContentObject_Release(arg1);
}


SWIGEXPORT void JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1AssertValid(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  ccnxContentObject_AssertValid((CCNxTlvDictionary const *)arg1);
}


SWIGEXPORT jstring JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1ToString(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jstring jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  result = (char *)ccnxContentObject_ToString((CCNxTlvDictionary const *)arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1Equals(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jboolean jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  CCNxContentObject *arg2 = (CCNxContentObject *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  arg2 = *(CCNxContentObject **)&jarg2; 
  result = (bool)ccnxContentObject_Equals((CCNxTlvDictionary const *)arg1,(CCNxTlvDictionary const *)arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jobject JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1GetExpiryTime(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jobject jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  uint64_t result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  result = (uint64_t)ccnxContentObject_GetExpiryTime((CCNxTlvDictionary const *)arg1);
  {
    jbyteArray ba = (*jenv)->NewByteArray(jenv, 9);
    jbyte* bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    jclass clazz = (*jenv)->FindClass(jenv, "java/math/BigInteger");
    jmethodID mid = (*jenv)->GetMethodID(jenv, clazz, "<init>", "([B)V");
    jobject bigint;
    int i;
    
    bae[0] = 0;
    for(i=1; i<9; i++ ) {
      bae[i] = (jbyte)(result>>8*(8-i));
    }
    
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
    bigint = (*jenv)->NewObject(jenv, clazz, mid, ba);
    jresult = bigint;
  }
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1SetExpiryTime(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg2) {
  jboolean jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  uint64_t arg2 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  {
    jclass clazz;
    jmethodID mid;
    jbyteArray ba;
    jbyte* bae;
    jsize sz;
    int i;
    
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "BigInteger null");
      return 0;
    }
    clazz = (*jenv)->GetObjectClass(jenv, jarg2);
    mid = (*jenv)->GetMethodID(jenv, clazz, "toByteArray", "()[B");
    ba = (jbyteArray)(*jenv)->CallObjectMethod(jenv, jarg2, mid);
    bae = (*jenv)->GetByteArrayElements(jenv, ba, 0);
    sz = (*jenv)->GetArrayLength(jenv, ba);
    arg2 = 0;
    for(i=0; i<sz; i++) {
      arg2 = (arg2 << 8) | (uint64_t const)(unsigned char)bae[i];
    }
    (*jenv)->ReleaseByteArrayElements(jenv, ba, bae, 0);
  }
  result = (bool)ccnxContentObject_SetExpiryTime(arg1,arg2);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1HasExpiryTime(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jboolean jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  result = (bool)ccnxContentObject_HasExpiryTime((CCNxTlvDictionary const *)arg1);
  jresult = (jboolean)result; 
  return jresult;
}


SWIGEXPORT jboolean JNICALL Java_ccnx_common_CcnxContentObject_ccnxContentObject_1SetPayload(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jboolean jresult = 0 ;
  CCNxContentObject *arg1 = (CCNxContentObject *) 0 ;
  CCNxPayloadType arg2 ;
  PARCBuffer *arg3 = (PARCBuffer *) 0 ;
  CCNxPayloadType *argp2 ;
  bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(CCNxContentObject **)&jarg1; 
  argp2 = *(CCNxPayloadType **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null CCNxPayloadType");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = *(PARCBuffer **)&jarg3; 
  result = (bool)ccnxContentObject_SetPayload(arg1,arg2,(PARCBuffer const *)arg3);
  jresult = (jboolean)result; 
  return jresult;
}


#ifdef __cplusplus
}
#endif

